# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rex.ying0923/main/CS/algo/research/DTW-approx

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rex.ying0923/main/CS/algo/research/DTW-approx

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest.exe --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rex.ying0923/main/CS/algo/research/DTW-approx/CMakeFiles /home/rex.ying0923/main/CS/algo/research/DTW-approx/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rex.ying0923/main/CS/algo/research/DTW-approx/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Frechet

# Build rule for target.
Frechet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Frechet
.PHONY : Frechet

# fast build rule for target.
Frechet/fast:
	$(MAKE) -f CMakeFiles/Frechet.dir/build.make CMakeFiles/Frechet.dir/build
.PHONY : Frechet/fast

#=============================================================================
# Target rules for targets named RectClusterTest

# Build rule for target.
RectClusterTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RectClusterTest
.PHONY : RectClusterTest

# fast build rule for target.
RectClusterTest/fast:
	$(MAKE) -f CMakeFiles/RectClusterTest.dir/build.make CMakeFiles/RectClusterTest.dir/build
.PHONY : RectClusterTest/fast

#=============================================================================
# Target rules for targets named RectShortestPathTest

# Build rule for target.
RectShortestPathTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RectShortestPathTest
.PHONY : RectShortestPathTest

# fast build rule for target.
RectShortestPathTest/fast:
	$(MAKE) -f CMakeFiles/RectShortestPathTest.dir/build.make CMakeFiles/RectShortestPathTest.dir/build
.PHONY : RectShortestPathTest/fast

#=============================================================================
# Target rules for targets named SequentialWSPDTest

# Build rule for target.
SequentialWSPDTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SequentialWSPDTest
.PHONY : SequentialWSPDTest

# fast build rule for target.
SequentialWSPDTest/fast:
	$(MAKE) -f CMakeFiles/SequentialWSPDTest.dir/build.make CMakeFiles/SequentialWSPDTest.dir/build
.PHONY : SequentialWSPDTest/fast

#=============================================================================
# Target rules for targets named Util

# Build rule for target.
Util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Util
.PHONY : Util

# fast build rule for target.
Util/fast:
	$(MAKE) -f CMakeFiles/Util.dir/build.make CMakeFiles/Util.dir/build
.PHONY : Util/fast

#=============================================================================
# Target rules for targets named WSPD

# Build rule for target.
WSPD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WSPD
.PHONY : WSPD

# fast build rule for target.
WSPD/fast:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/build
.PHONY : WSPD/fast

#=============================================================================
# Target rules for targets named curve_registration

# Build rule for target.
curve_registration: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 curve_registration
.PHONY : curve_registration

# fast build rule for target.
curve_registration/fast:
	$(MAKE) -f CMakeFiles/curve_registration.dir/build.make CMakeFiles/curve_registration.dir/build
.PHONY : curve_registration/fast

#=============================================================================
# Target rules for targets named executable

# Build rule for target.
executable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 executable
.PHONY : executable

# fast build rule for target.
executable/fast:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/build
.PHONY : executable/fast

#=============================================================================
# Target rules for targets named gen_tests

# Build rule for target.
gen_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gen_tests
.PHONY : gen_tests

# fast build rule for target.
gen_tests/fast:
	$(MAKE) -f CMakeFiles/gen_tests.dir/build.make CMakeFiles/gen_tests.dir/build
.PHONY : gen_tests/fast

FrechetDecider.o: FrechetDecider.cpp.o

.PHONY : FrechetDecider.o

# target to build an object file
FrechetDecider.cpp.o:
	$(MAKE) -f CMakeFiles/Frechet.dir/build.make CMakeFiles/Frechet.dir/FrechetDecider.cpp.o
.PHONY : FrechetDecider.cpp.o

FrechetDecider.i: FrechetDecider.cpp.i

.PHONY : FrechetDecider.i

# target to preprocess a source file
FrechetDecider.cpp.i:
	$(MAKE) -f CMakeFiles/Frechet.dir/build.make CMakeFiles/Frechet.dir/FrechetDecider.cpp.i
.PHONY : FrechetDecider.cpp.i

FrechetDecider.s: FrechetDecider.cpp.s

.PHONY : FrechetDecider.s

# target to generate assembly for a file
FrechetDecider.cpp.s:
	$(MAKE) -f CMakeFiles/Frechet.dir/build.make CMakeFiles/Frechet.dir/FrechetDecider.cpp.s
.PHONY : FrechetDecider.cpp.s

QuadTree.o: QuadTree.cpp.o

.PHONY : QuadTree.o

# target to build an object file
QuadTree.cpp.o:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/QuadTree.cpp.o
.PHONY : QuadTree.cpp.o

QuadTree.i: QuadTree.cpp.i

.PHONY : QuadTree.i

# target to preprocess a source file
QuadTree.cpp.i:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/QuadTree.cpp.i
.PHONY : QuadTree.cpp.i

QuadTree.s: QuadTree.cpp.s

.PHONY : QuadTree.s

# target to generate assembly for a file
QuadTree.cpp.s:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/QuadTree.cpp.s
.PHONY : QuadTree.cpp.s

QuadTreeTwoClasses.o: QuadTreeTwoClasses.cpp.o

.PHONY : QuadTreeTwoClasses.o

# target to build an object file
QuadTreeTwoClasses.cpp.o:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/QuadTreeTwoClasses.cpp.o
.PHONY : QuadTreeTwoClasses.cpp.o

QuadTreeTwoClasses.i: QuadTreeTwoClasses.cpp.i

.PHONY : QuadTreeTwoClasses.i

# target to preprocess a source file
QuadTreeTwoClasses.cpp.i:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/QuadTreeTwoClasses.cpp.i
.PHONY : QuadTreeTwoClasses.cpp.i

QuadTreeTwoClasses.s: QuadTreeTwoClasses.cpp.s

.PHONY : QuadTreeTwoClasses.s

# target to generate assembly for a file
QuadTreeTwoClasses.cpp.s:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/QuadTreeTwoClasses.cpp.s
.PHONY : QuadTreeTwoClasses.cpp.s

WSPD.o: WSPD.cpp.o

.PHONY : WSPD.o

# target to build an object file
WSPD.cpp.o:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/WSPD.cpp.o
.PHONY : WSPD.cpp.o

WSPD.i: WSPD.cpp.i

.PHONY : WSPD.i

# target to preprocess a source file
WSPD.cpp.i:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/WSPD.cpp.i
.PHONY : WSPD.cpp.i

WSPD.s: WSPD.cpp.s

.PHONY : WSPD.s

# target to generate assembly for a file
WSPD.cpp.s:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/WSPD.cpp.s
.PHONY : WSPD.cpp.s

curve_registration.o: curve_registration.cpp.o

.PHONY : curve_registration.o

# target to build an object file
curve_registration.cpp.o:
	$(MAKE) -f CMakeFiles/curve_registration.dir/build.make CMakeFiles/curve_registration.dir/curve_registration.cpp.o
.PHONY : curve_registration.cpp.o

curve_registration.i: curve_registration.cpp.i

.PHONY : curve_registration.i

# target to preprocess a source file
curve_registration.cpp.i:
	$(MAKE) -f CMakeFiles/curve_registration.dir/build.make CMakeFiles/curve_registration.dir/curve_registration.cpp.i
.PHONY : curve_registration.cpp.i

curve_registration.s: curve_registration.cpp.s

.PHONY : curve_registration.s

# target to generate assembly for a file
curve_registration.cpp.s:
	$(MAKE) -f CMakeFiles/curve_registration.dir/build.make CMakeFiles/curve_registration.dir/curve_registration.cpp.s
.PHONY : curve_registration.cpp.s

curvegen/curve_generator.o: curvegen/curve_generator.cpp.o

.PHONY : curvegen/curve_generator.o

# target to build an object file
curvegen/curve_generator.cpp.o:
	$(MAKE) -f CMakeFiles/gen_tests.dir/build.make CMakeFiles/gen_tests.dir/curvegen/curve_generator.cpp.o
.PHONY : curvegen/curve_generator.cpp.o

curvegen/curve_generator.i: curvegen/curve_generator.cpp.i

.PHONY : curvegen/curve_generator.i

# target to preprocess a source file
curvegen/curve_generator.cpp.i:
	$(MAKE) -f CMakeFiles/gen_tests.dir/build.make CMakeFiles/gen_tests.dir/curvegen/curve_generator.cpp.i
.PHONY : curvegen/curve_generator.cpp.i

curvegen/curve_generator.s: curvegen/curve_generator.cpp.s

.PHONY : curvegen/curve_generator.s

# target to generate assembly for a file
curvegen/curve_generator.cpp.s:
	$(MAKE) -f CMakeFiles/gen_tests.dir/build.make CMakeFiles/gen_tests.dir/curvegen/curve_generator.cpp.s
.PHONY : curvegen/curve_generator.cpp.s

curvegen/gen_tests.o: curvegen/gen_tests.cpp.o

.PHONY : curvegen/gen_tests.o

# target to build an object file
curvegen/gen_tests.cpp.o:
	$(MAKE) -f CMakeFiles/gen_tests.dir/build.make CMakeFiles/gen_tests.dir/curvegen/gen_tests.cpp.o
.PHONY : curvegen/gen_tests.cpp.o

curvegen/gen_tests.i: curvegen/gen_tests.cpp.i

.PHONY : curvegen/gen_tests.i

# target to preprocess a source file
curvegen/gen_tests.cpp.i:
	$(MAKE) -f CMakeFiles/gen_tests.dir/build.make CMakeFiles/gen_tests.dir/curvegen/gen_tests.cpp.i
.PHONY : curvegen/gen_tests.cpp.i

curvegen/gen_tests.s: curvegen/gen_tests.cpp.s

.PHONY : curvegen/gen_tests.s

# target to generate assembly for a file
curvegen/gen_tests.cpp.s:
	$(MAKE) -f CMakeFiles/gen_tests.dir/build.make CMakeFiles/gen_tests.dir/curvegen/gen_tests.cpp.s
.PHONY : curvegen/gen_tests.cpp.s

frechet.o: frechet.cpp.o

.PHONY : frechet.o

# target to build an object file
frechet.cpp.o:
	$(MAKE) -f CMakeFiles/Frechet.dir/build.make CMakeFiles/Frechet.dir/frechet.cpp.o
.PHONY : frechet.cpp.o

frechet.i: frechet.cpp.i

.PHONY : frechet.i

# target to preprocess a source file
frechet.cpp.i:
	$(MAKE) -f CMakeFiles/Frechet.dir/build.make CMakeFiles/Frechet.dir/frechet.cpp.i
.PHONY : frechet.cpp.i

frechet.s: frechet.cpp.s

.PHONY : frechet.s

# target to generate assembly for a file
frechet.cpp.s:
	$(MAKE) -f CMakeFiles/Frechet.dir/build.make CMakeFiles/Frechet.dir/frechet.cpp.s
.PHONY : frechet.cpp.s

grid.o: grid.cpp.o

.PHONY : grid.o

# target to build an object file
grid.cpp.o:
	$(MAKE) -f CMakeFiles/RectClusterTest.dir/build.make CMakeFiles/RectClusterTest.dir/grid.cpp.o
	$(MAKE) -f CMakeFiles/RectShortestPathTest.dir/build.make CMakeFiles/RectShortestPathTest.dir/grid.cpp.o
	$(MAKE) -f CMakeFiles/SequentialWSPDTest.dir/build.make CMakeFiles/SequentialWSPDTest.dir/grid.cpp.o
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/grid.cpp.o
.PHONY : grid.cpp.o

grid.i: grid.cpp.i

.PHONY : grid.i

# target to preprocess a source file
grid.cpp.i:
	$(MAKE) -f CMakeFiles/RectClusterTest.dir/build.make CMakeFiles/RectClusterTest.dir/grid.cpp.i
	$(MAKE) -f CMakeFiles/RectShortestPathTest.dir/build.make CMakeFiles/RectShortestPathTest.dir/grid.cpp.i
	$(MAKE) -f CMakeFiles/SequentialWSPDTest.dir/build.make CMakeFiles/SequentialWSPDTest.dir/grid.cpp.i
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/grid.cpp.i
.PHONY : grid.cpp.i

grid.s: grid.cpp.s

.PHONY : grid.s

# target to generate assembly for a file
grid.cpp.s:
	$(MAKE) -f CMakeFiles/RectClusterTest.dir/build.make CMakeFiles/RectClusterTest.dir/grid.cpp.s
	$(MAKE) -f CMakeFiles/RectShortestPathTest.dir/build.make CMakeFiles/RectShortestPathTest.dir/grid.cpp.s
	$(MAKE) -f CMakeFiles/SequentialWSPDTest.dir/build.make CMakeFiles/SequentialWSPDTest.dir/grid.cpp.s
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/grid.cpp.s
.PHONY : grid.cpp.s

icp.o: icp.cpp.o

.PHONY : icp.o

# target to build an object file
icp.cpp.o:
	$(MAKE) -f CMakeFiles/curve_registration.dir/build.make CMakeFiles/curve_registration.dir/icp.cpp.o
.PHONY : icp.cpp.o

icp.i: icp.cpp.i

.PHONY : icp.i

# target to preprocess a source file
icp.cpp.i:
	$(MAKE) -f CMakeFiles/curve_registration.dir/build.make CMakeFiles/curve_registration.dir/icp.cpp.i
.PHONY : icp.cpp.i

icp.s: icp.cpp.s

.PHONY : icp.s

# target to generate assembly for a file
icp.cpp.s:
	$(MAKE) -f CMakeFiles/curve_registration.dir/build.make CMakeFiles/curve_registration.dir/icp.cpp.s
.PHONY : icp.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/main.cpp.s
.PHONY : main.cpp.s

naive_dtw.o: naive_dtw.cpp.o

.PHONY : naive_dtw.o

# target to build an object file
naive_dtw.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/naive_dtw.cpp.o
.PHONY : naive_dtw.cpp.o

naive_dtw.i: naive_dtw.cpp.i

.PHONY : naive_dtw.i

# target to preprocess a source file
naive_dtw.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/naive_dtw.cpp.i
.PHONY : naive_dtw.cpp.i

naive_dtw.s: naive_dtw.cpp.s

.PHONY : naive_dtw.s

# target to generate assembly for a file
naive_dtw.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/naive_dtw.cpp.s
.PHONY : naive_dtw.cpp.s

rect_cluster.o: rect_cluster.cpp.o

.PHONY : rect_cluster.o

# target to build an object file
rect_cluster.cpp.o:
	$(MAKE) -f CMakeFiles/RectClusterTest.dir/build.make CMakeFiles/RectClusterTest.dir/rect_cluster.cpp.o
	$(MAKE) -f CMakeFiles/RectShortestPathTest.dir/build.make CMakeFiles/RectShortestPathTest.dir/rect_cluster.cpp.o
	$(MAKE) -f CMakeFiles/SequentialWSPDTest.dir/build.make CMakeFiles/SequentialWSPDTest.dir/rect_cluster.cpp.o
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/rect_cluster.cpp.o
.PHONY : rect_cluster.cpp.o

rect_cluster.i: rect_cluster.cpp.i

.PHONY : rect_cluster.i

# target to preprocess a source file
rect_cluster.cpp.i:
	$(MAKE) -f CMakeFiles/RectClusterTest.dir/build.make CMakeFiles/RectClusterTest.dir/rect_cluster.cpp.i
	$(MAKE) -f CMakeFiles/RectShortestPathTest.dir/build.make CMakeFiles/RectShortestPathTest.dir/rect_cluster.cpp.i
	$(MAKE) -f CMakeFiles/SequentialWSPDTest.dir/build.make CMakeFiles/SequentialWSPDTest.dir/rect_cluster.cpp.i
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/rect_cluster.cpp.i
.PHONY : rect_cluster.cpp.i

rect_cluster.s: rect_cluster.cpp.s

.PHONY : rect_cluster.s

# target to generate assembly for a file
rect_cluster.cpp.s:
	$(MAKE) -f CMakeFiles/RectClusterTest.dir/build.make CMakeFiles/RectClusterTest.dir/rect_cluster.cpp.s
	$(MAKE) -f CMakeFiles/RectShortestPathTest.dir/build.make CMakeFiles/RectShortestPathTest.dir/rect_cluster.cpp.s
	$(MAKE) -f CMakeFiles/SequentialWSPDTest.dir/build.make CMakeFiles/SequentialWSPDTest.dir/rect_cluster.cpp.s
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/rect_cluster.cpp.s
.PHONY : rect_cluster.cpp.s

rect_shortest_path.o: rect_shortest_path.cpp.o

.PHONY : rect_shortest_path.o

# target to build an object file
rect_shortest_path.cpp.o:
	$(MAKE) -f CMakeFiles/RectClusterTest.dir/build.make CMakeFiles/RectClusterTest.dir/rect_shortest_path.cpp.o
	$(MAKE) -f CMakeFiles/RectShortestPathTest.dir/build.make CMakeFiles/RectShortestPathTest.dir/rect_shortest_path.cpp.o
	$(MAKE) -f CMakeFiles/SequentialWSPDTest.dir/build.make CMakeFiles/SequentialWSPDTest.dir/rect_shortest_path.cpp.o
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/rect_shortest_path.cpp.o
.PHONY : rect_shortest_path.cpp.o

rect_shortest_path.i: rect_shortest_path.cpp.i

.PHONY : rect_shortest_path.i

# target to preprocess a source file
rect_shortest_path.cpp.i:
	$(MAKE) -f CMakeFiles/RectClusterTest.dir/build.make CMakeFiles/RectClusterTest.dir/rect_shortest_path.cpp.i
	$(MAKE) -f CMakeFiles/RectShortestPathTest.dir/build.make CMakeFiles/RectShortestPathTest.dir/rect_shortest_path.cpp.i
	$(MAKE) -f CMakeFiles/SequentialWSPDTest.dir/build.make CMakeFiles/SequentialWSPDTest.dir/rect_shortest_path.cpp.i
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/rect_shortest_path.cpp.i
.PHONY : rect_shortest_path.cpp.i

rect_shortest_path.s: rect_shortest_path.cpp.s

.PHONY : rect_shortest_path.s

# target to generate assembly for a file
rect_shortest_path.cpp.s:
	$(MAKE) -f CMakeFiles/RectClusterTest.dir/build.make CMakeFiles/RectClusterTest.dir/rect_shortest_path.cpp.s
	$(MAKE) -f CMakeFiles/RectShortestPathTest.dir/build.make CMakeFiles/RectShortestPathTest.dir/rect_shortest_path.cpp.s
	$(MAKE) -f CMakeFiles/SequentialWSPDTest.dir/build.make CMakeFiles/SequentialWSPDTest.dir/rect_shortest_path.cpp.s
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/rect_shortest_path.cpp.s
.PHONY : rect_shortest_path.cpp.s

sequential_wspd.o: sequential_wspd.cpp.o

.PHONY : sequential_wspd.o

# target to build an object file
sequential_wspd.cpp.o:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/sequential_wspd.cpp.o
.PHONY : sequential_wspd.cpp.o

sequential_wspd.i: sequential_wspd.cpp.i

.PHONY : sequential_wspd.i

# target to preprocess a source file
sequential_wspd.cpp.i:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/sequential_wspd.cpp.i
.PHONY : sequential_wspd.cpp.i

sequential_wspd.s: sequential_wspd.cpp.s

.PHONY : sequential_wspd.s

# target to generate assembly for a file
sequential_wspd.cpp.s:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/sequential_wspd.cpp.s
.PHONY : sequential_wspd.cpp.s

tests/rect_cluster_test.o: tests/rect_cluster_test.cpp.o

.PHONY : tests/rect_cluster_test.o

# target to build an object file
tests/rect_cluster_test.cpp.o:
	$(MAKE) -f CMakeFiles/RectClusterTest.dir/build.make CMakeFiles/RectClusterTest.dir/tests/rect_cluster_test.cpp.o
.PHONY : tests/rect_cluster_test.cpp.o

tests/rect_cluster_test.i: tests/rect_cluster_test.cpp.i

.PHONY : tests/rect_cluster_test.i

# target to preprocess a source file
tests/rect_cluster_test.cpp.i:
	$(MAKE) -f CMakeFiles/RectClusterTest.dir/build.make CMakeFiles/RectClusterTest.dir/tests/rect_cluster_test.cpp.i
.PHONY : tests/rect_cluster_test.cpp.i

tests/rect_cluster_test.s: tests/rect_cluster_test.cpp.s

.PHONY : tests/rect_cluster_test.s

# target to generate assembly for a file
tests/rect_cluster_test.cpp.s:
	$(MAKE) -f CMakeFiles/RectClusterTest.dir/build.make CMakeFiles/RectClusterTest.dir/tests/rect_cluster_test.cpp.s
.PHONY : tests/rect_cluster_test.cpp.s

tests/rect_shortest_path_test.o: tests/rect_shortest_path_test.cpp.o

.PHONY : tests/rect_shortest_path_test.o

# target to build an object file
tests/rect_shortest_path_test.cpp.o:
	$(MAKE) -f CMakeFiles/RectShortestPathTest.dir/build.make CMakeFiles/RectShortestPathTest.dir/tests/rect_shortest_path_test.cpp.o
.PHONY : tests/rect_shortest_path_test.cpp.o

tests/rect_shortest_path_test.i: tests/rect_shortest_path_test.cpp.i

.PHONY : tests/rect_shortest_path_test.i

# target to preprocess a source file
tests/rect_shortest_path_test.cpp.i:
	$(MAKE) -f CMakeFiles/RectShortestPathTest.dir/build.make CMakeFiles/RectShortestPathTest.dir/tests/rect_shortest_path_test.cpp.i
.PHONY : tests/rect_shortest_path_test.cpp.i

tests/rect_shortest_path_test.s: tests/rect_shortest_path_test.cpp.s

.PHONY : tests/rect_shortest_path_test.s

# target to generate assembly for a file
tests/rect_shortest_path_test.cpp.s:
	$(MAKE) -f CMakeFiles/RectShortestPathTest.dir/build.make CMakeFiles/RectShortestPathTest.dir/tests/rect_shortest_path_test.cpp.s
.PHONY : tests/rect_shortest_path_test.cpp.s

tests/sequential_wspd_test.o: tests/sequential_wspd_test.cpp.o

.PHONY : tests/sequential_wspd_test.o

# target to build an object file
tests/sequential_wspd_test.cpp.o:
	$(MAKE) -f CMakeFiles/SequentialWSPDTest.dir/build.make CMakeFiles/SequentialWSPDTest.dir/tests/sequential_wspd_test.cpp.o
.PHONY : tests/sequential_wspd_test.cpp.o

tests/sequential_wspd_test.i: tests/sequential_wspd_test.cpp.i

.PHONY : tests/sequential_wspd_test.i

# target to preprocess a source file
tests/sequential_wspd_test.cpp.i:
	$(MAKE) -f CMakeFiles/SequentialWSPDTest.dir/build.make CMakeFiles/SequentialWSPDTest.dir/tests/sequential_wspd_test.cpp.i
.PHONY : tests/sequential_wspd_test.cpp.i

tests/sequential_wspd_test.s: tests/sequential_wspd_test.cpp.s

.PHONY : tests/sequential_wspd_test.s

# target to generate assembly for a file
tests/sequential_wspd_test.cpp.s:
	$(MAKE) -f CMakeFiles/SequentialWSPDTest.dir/build.make CMakeFiles/SequentialWSPDTest.dir/tests/sequential_wspd_test.cpp.s
.PHONY : tests/sequential_wspd_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... WSPD"
	@echo "... Frechet"
	@echo "... Util"
	@echo "... gen_tests"
	@echo "... rebuild_cache"
	@echo "... executable"
	@echo "... SequentialWSPDTest"
	@echo "... RectClusterTest"
	@echo "... curve_registration"
	@echo "... RectShortestPathTest"
	@echo "... FrechetDecider.o"
	@echo "... FrechetDecider.i"
	@echo "... FrechetDecider.s"
	@echo "... QuadTree.o"
	@echo "... QuadTree.i"
	@echo "... QuadTree.s"
	@echo "... QuadTreeTwoClasses.o"
	@echo "... QuadTreeTwoClasses.i"
	@echo "... QuadTreeTwoClasses.s"
	@echo "... WSPD.o"
	@echo "... WSPD.i"
	@echo "... WSPD.s"
	@echo "... curve_registration.o"
	@echo "... curve_registration.i"
	@echo "... curve_registration.s"
	@echo "... curvegen/curve_generator.o"
	@echo "... curvegen/curve_generator.i"
	@echo "... curvegen/curve_generator.s"
	@echo "... curvegen/gen_tests.o"
	@echo "... curvegen/gen_tests.i"
	@echo "... curvegen/gen_tests.s"
	@echo "... frechet.o"
	@echo "... frechet.i"
	@echo "... frechet.s"
	@echo "... grid.o"
	@echo "... grid.i"
	@echo "... grid.s"
	@echo "... icp.o"
	@echo "... icp.i"
	@echo "... icp.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... naive_dtw.o"
	@echo "... naive_dtw.i"
	@echo "... naive_dtw.s"
	@echo "... rect_cluster.o"
	@echo "... rect_cluster.i"
	@echo "... rect_cluster.s"
	@echo "... rect_shortest_path.o"
	@echo "... rect_shortest_path.i"
	@echo "... rect_shortest_path.s"
	@echo "... sequential_wspd.o"
	@echo "... sequential_wspd.i"
	@echo "... sequential_wspd.s"
	@echo "... tests/rect_cluster_test.o"
	@echo "... tests/rect_cluster_test.i"
	@echo "... tests/rect_cluster_test.s"
	@echo "... tests/rect_shortest_path_test.o"
	@echo "... tests/rect_shortest_path_test.i"
	@echo "... tests/rect_shortest_path_test.s"
	@echo "... tests/sequential_wspd_test.o"
	@echo "... tests/sequential_wspd_test.i"
	@echo "... tests/sequential_wspd_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

