# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rex/Desktop/work/linux/algo/DTW-approx

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rex/Desktop/work/linux/algo/DTW-approx

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rex/Desktop/work/linux/algo/DTW-approx/CMakeFiles /home/rex/Desktop/work/linux/algo/DTW-approx/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rex/Desktop/work/linux/algo/DTW-approx/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Frechet

# Build rule for target.
Frechet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Frechet
.PHONY : Frechet

# fast build rule for target.
Frechet/fast:
	$(MAKE) -f CMakeFiles/Frechet.dir/build.make CMakeFiles/Frechet.dir/build
.PHONY : Frechet/fast

#=============================================================================
# Target rules for targets named WSPD

# Build rule for target.
WSPD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WSPD
.PHONY : WSPD

# fast build rule for target.
WSPD/fast:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/build
.PHONY : WSPD/fast

#=============================================================================
# Target rules for targets named executable

# Build rule for target.
executable: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 executable
.PHONY : executable

# fast build rule for target.
executable/fast:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/build
.PHONY : executable/fast

FrechetDecider.o: FrechetDecider.cpp.o
.PHONY : FrechetDecider.o

# target to build an object file
FrechetDecider.cpp.o:
	$(MAKE) -f CMakeFiles/Frechet.dir/build.make CMakeFiles/Frechet.dir/FrechetDecider.cpp.o
.PHONY : FrechetDecider.cpp.o

FrechetDecider.i: FrechetDecider.cpp.i
.PHONY : FrechetDecider.i

# target to preprocess a source file
FrechetDecider.cpp.i:
	$(MAKE) -f CMakeFiles/Frechet.dir/build.make CMakeFiles/Frechet.dir/FrechetDecider.cpp.i
.PHONY : FrechetDecider.cpp.i

FrechetDecider.s: FrechetDecider.cpp.s
.PHONY : FrechetDecider.s

# target to generate assembly for a file
FrechetDecider.cpp.s:
	$(MAKE) -f CMakeFiles/Frechet.dir/build.make CMakeFiles/Frechet.dir/FrechetDecider.cpp.s
.PHONY : FrechetDecider.cpp.s

QuadTree.o: QuadTree.cpp.o
.PHONY : QuadTree.o

# target to build an object file
QuadTree.cpp.o:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/QuadTree.cpp.o
.PHONY : QuadTree.cpp.o

QuadTree.i: QuadTree.cpp.i
.PHONY : QuadTree.i

# target to preprocess a source file
QuadTree.cpp.i:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/QuadTree.cpp.i
.PHONY : QuadTree.cpp.i

QuadTree.s: QuadTree.cpp.s
.PHONY : QuadTree.s

# target to generate assembly for a file
QuadTree.cpp.s:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/QuadTree.cpp.s
.PHONY : QuadTree.cpp.s

QuadTreeTwoClasses.o: QuadTreeTwoClasses.cpp.o
.PHONY : QuadTreeTwoClasses.o

# target to build an object file
QuadTreeTwoClasses.cpp.o:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/QuadTreeTwoClasses.cpp.o
.PHONY : QuadTreeTwoClasses.cpp.o

QuadTreeTwoClasses.i: QuadTreeTwoClasses.cpp.i
.PHONY : QuadTreeTwoClasses.i

# target to preprocess a source file
QuadTreeTwoClasses.cpp.i:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/QuadTreeTwoClasses.cpp.i
.PHONY : QuadTreeTwoClasses.cpp.i

QuadTreeTwoClasses.s: QuadTreeTwoClasses.cpp.s
.PHONY : QuadTreeTwoClasses.s

# target to generate assembly for a file
QuadTreeTwoClasses.cpp.s:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/QuadTreeTwoClasses.cpp.s
.PHONY : QuadTreeTwoClasses.cpp.s

Sampling.o: Sampling.cpp.o
.PHONY : Sampling.o

# target to build an object file
Sampling.cpp.o:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/Sampling.cpp.o
.PHONY : Sampling.cpp.o

Sampling.i: Sampling.cpp.i
.PHONY : Sampling.i

# target to preprocess a source file
Sampling.cpp.i:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/Sampling.cpp.i
.PHONY : Sampling.cpp.i

Sampling.s: Sampling.cpp.s
.PHONY : Sampling.s

# target to generate assembly for a file
Sampling.cpp.s:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/Sampling.cpp.s
.PHONY : Sampling.cpp.s

WSPD.o: WSPD.cpp.o
.PHONY : WSPD.o

# target to build an object file
WSPD.cpp.o:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/WSPD.cpp.o
.PHONY : WSPD.cpp.o

WSPD.i: WSPD.cpp.i
.PHONY : WSPD.i

# target to preprocess a source file
WSPD.cpp.i:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/WSPD.cpp.i
.PHONY : WSPD.cpp.i

WSPD.s: WSPD.cpp.s
.PHONY : WSPD.s

# target to generate assembly for a file
WSPD.cpp.s:
	$(MAKE) -f CMakeFiles/WSPD.dir/build.make CMakeFiles/WSPD.dir/WSPD.cpp.s
.PHONY : WSPD.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/executable.dir/build.make CMakeFiles/executable.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Frechet"
	@echo "... WSPD"
	@echo "... edit_cache"
	@echo "... executable"
	@echo "... rebuild_cache"
	@echo "... FrechetDecider.o"
	@echo "... FrechetDecider.i"
	@echo "... FrechetDecider.s"
	@echo "... QuadTree.o"
	@echo "... QuadTree.i"
	@echo "... QuadTree.s"
	@echo "... QuadTreeTwoClasses.o"
	@echo "... QuadTreeTwoClasses.i"
	@echo "... QuadTreeTwoClasses.s"
	@echo "... Sampling.o"
	@echo "... Sampling.i"
	@echo "... Sampling.s"
	@echo "... WSPD.o"
	@echo "... WSPD.i"
	@echo "... WSPD.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

